using System;
using System.Collections.Generic;

namespace FescoFast.EFPowerTools.Models
{
    public partial class V_Gds_Dan_3
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string ParentNo { get; set; }
        public string Danno { get; set; }
        public int Fid { get; set; }
        public int Busid { get; set; }
        public int Fesid { get; set; }
        public int Ftype { get; set; }
        public int Addrid { get; set; }
        public string Shouman { get; set; }
        public string Shoultd { get; set; }
        public string Sex { get; set; }
        public int Provid { get; set; }
        public string Prov { get; set; }
        public int Xianid { get; set; }
        public string Xian { get; set; }
        public string Addr { get; set; }
        public string Postcode { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Bak { get; set; }
        public int ShouDayType { get; set; }
        public int ShouTimeType { get; set; }
        public int Paytype { get; set; }
        public int Yuntype { get; set; }
        public decimal Weight { get; set; }
        public decimal Yunfei { get; set; }
        public decimal MnyAll { get; set; }
        public decimal Decfei { get; set; }
        public decimal Mnypay { get; set; }
        public bool IsYouhui { get; set; }
        public string Youhuicode { get; set; }
        public int Gysid { get; set; }
        public string GysName { get; set; }
        public int Danstate { get; set; }
        public System.DateTime Dandate { get; set; }
        public System.DateTime Paydate { get; set; }
        public System.DateTime ConfirmDate { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime Shoudate { get; set; }
        public int Serv_Pleased { get; set; }
        public int Kds_Pleased { get; set; }
        public int Kdh_Pleased { get; set; }
        public int Kd_Pleased { get; set; }
        public int Goods_Pleased { get; set; }
        public string Pjbak { get; set; }
        public string Bak2 { get; set; }
        public bool Pjstate { get; set; }
        public string Bankseq { get; set; }
        public bool FapiaoState { get; set; }
        public string Fapiaotitle { get; set; }
        public string Fapiaotype { get; set; }
        public int PiaoType { get; set; }
        public string PiaoNumber { get; set; }
        public int Passid { get; set; }
        public string SoHuDanId { get; set; }
        public string SoHuSouDate { get; set; }
        public int SubDans { get; set; }
        public int GdsTs { get; set; }
        public decimal Danfei { get; set; }
        public decimal Zifubao { get; set; }
        public decimal Cardfei { get; set; }
        public bool State { get; set; }
        public decimal Fenpay { get; set; }
        public int Mtype { get; set; }
        public string Aplman { get; set; }
        public string Aplgonghao { get; set; }
        public System.DateTime Newdate { get; set; }
        public string Juanid { get; set; }
        public decimal Juan { get; set; }
        public int Dstate { get; set; }
        public int Tenid { get; set; }
        public int Hisdanstate { get; set; }
        public int Planid { get; set; }
        public string BAK3 { get; set; }
        public string Email { get; set; }
        public bool IsSohuSendOk { get; set; }
        public System.DateTime IsSohuOkDate { get; set; }
        public string OnceCardNum { get; set; }
        public Nullable<int> Hno { get; set; }
        public string Cname { get; set; }
        public string Ename { get; set; }
        public string Usedname { get; set; }
        public string Gno { get; set; }
        public string CardId { get; set; }
        public string UMobile { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string Fname { get; set; }
        public string Script { get; set; }
        public int Source { get; set; }
        public string Yewubu { get; set; }
        public string YewubuUser { get; set; }
        public string DanScript { get; set; }
    }
}
