CREATE LOGIN [fescohmse]
    WITH PASSWORD = N'SuJniWqulawmne$cb%LTvp6lmsFT7_&#$!~<pxwfp$nokyms', SID = 0xDFE1633FDE32C54D8AE1B2AED348CF68, DEFAULT_DATABASE = [FesMvc407], DEFAULT_LANGUAGE = [简体中文], CHECK_POLICY = OFF;

