/****** Object:  StoredProcedure [dbo].[PROC_CLEAN_DATA]    Script Date: 05/14/2018 14:36:58 ******/
CREATE PROCEDURE [dbo].[PROC_CLEAN_DATA]
AS 
BEGIN 
DECLARE @ACCOUNTID INT,
@ACCENO NVARCHAR(50);
--创建需要修改的民族字典游标
DECLARE CUR_UPDATED_LIST CURSOR FAST_FORWARD FOR
SELECT ACCOUNTID,ACCE_NO FROM T_JC_Account_AttachData WHERE SEND_LOGIN_NAME='ywy802';

OPEN CUR_UPDATED_LIST;
	
	FETCH NEXT FROM CUR_UPDATED_LIST INTO @ACCOUNTID,@ACCENO;

	WHILE @@FETCH_STATUS=0
		BEGIN 	
			 UPDATE T_JC_TaskUnit SET AccountID=@ACCOUNTID WHERE ACCE_NO=@ACCENO;
		-- 取下一条记录
		FETCH NEXT FROM CUR_UPDATED_LIST INTO @ACCOUNTID,@ACCENO;
		END


CLOSE CUR_UPDATED_LIST;

DEALLOCATE CUR_UPDATED_LIST;

END;